// movies
export const FETCHED_MOVIES = "FETCHED_MOVIES";
export const FETCHED_MOVIE = "FETCHED_MOVIE";
export const FETCHED_MOVIES_PENDING = "FETCHED_MOVIE_PENDING";
export const FETCHED_MOVIES_ERROR = "FETCHED_MOVIE_ERROR";

// reviews
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_TOPIC = "UPDATE_TOPIC";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const SET_REVIEWS = "SET_REVIEWS";
export const RESET_REVIEW_INPUT = "RESET_REVIEW_INPUT";
