export const FETCHED_MOVIES = "FETCHED_MOVIES";
export const FETCHED_MOVIE = "FETCHED_MOVIE";
export const FETCHED_MOVIES_PENDING = "FETCHED_MOVIE_PENDING";
export const FETCHED_MOVIES_ERROR = "FETCHED_MOVIE_ERROR";
